name: Test

on: [pull_request]

jobs:
  go-test:
    name: "Go Test"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run Mage
        uses: crazy-max/ghaction-mage@v1
        with:
          version: latest
          args: test
  go-mod-tidy:
    name: "Go mod tidy"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run Mage
        uses: crazy-max/ghaction-mage@v1
        with:
          version: latest
          args: gomodtidy
